// vue/src/layout/LayoutContent.vue
<template>
  <div class="layout-content" :style="extraStyle">
    <div class="layout-content__main">
      <slot name="content"></slot>
    </div>
    <div class="layout-content__corner">
      <img
        v-if="cornerVisible"
        class="corner-img"
        :class="cornerPosition"
        src="../assets/corner.png"
        alt=""
      />
    </div>
  </div>
</template>

<script>
export default {
  name: "",
  props: {
    title: String,
    cornerVisible: {
      type: Boolean,
      default: true,
    },
    cornerPosition: {
      type: String,
      default: "bottom-left",
    },
    extraStyle: Object,
  },
};
</script>

<style scoped lang="less">
@import url("../styles/layout/layoutContent.less");
</style>

// src/layout/LayoutContent.tsx
import React from 'react'

import 'src/styles/layout/layoutContent.less'

type Props = {
  title?: string,
  cornerVisible?: boolean,
  cornerPosition?: 'bottom-left' | 'bottom-right' | 'top-left' | 'top-right',
  style?: any,
  [propsName: string]: any
}

const LayoutContent = (props: Props) => {
  const { title, cornerVisible, cornerPosition, style } = props
  return (
    <div className='layout-content' style={style}>
      <div className="layout-content__title">{title}</div>
      <div className="layout-content__main">{props.children}</div>
      <div className="layout-content__corner" >
        {
          cornerVisible && (
            <img
              className={`corner-img ${cornerPosition}`}
              src={require('../assets/corner.png')}
              alt="" />
          )
        }
      </div>
    </div>
  )
}

LayoutContent.defaultProps = {
  cornerVisible: true,
  cornerPosition: 'bottom-left',
  style: {}
}

export default LayoutContent
